apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-folders-configmap
data:
  mysqlDB: "mysql.cert.com:3306"
  paypal_url: "cert.app1-folders.com"
  environment: "cert"
  environment_type: "folders"
  UI_THEME: "light"
  N_BUCKETS: "2"
