apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redmine-project
  namespace: argocd-platform
spec:
  description: Project for Redmine and PostgreSQL applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: redmine
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
