apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine-postgresql-app
  namespace: argocd-platform
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelName
spec:
  project: redmine-project
  source:
    repoURL: 'https://github.com/MToscanoM/gitops-labs.git'
    targetRevision: HEAD
    path: aplicaciones/redmine
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redmine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: ''
    kind: Secret
    jsonPointers:
    - /data
