apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-kustomize-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /pocs/cert/app1-kustomize
