# Utilizar una imagen base oficial de Nginx
FROM nginx:alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/share/nginx/html

# Copiar los archivos HTML y CSS al directorio de trabajo del contenedor
COPY ./source/ /usr/share/nginx/html

# Exponer el puerto 80 para el contenedor
EXPOSE 80

# No es necesario especificar CMD porque la imagen oficial de Nginx ya lo hace por defecto