apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: 'true' # disables https for argocd-server
  server.basehref: /argocd/
  server.rootpath: /argocd/
  server.repo.server.timeout.seconds: "60"