Vagrant.configure("2") do |config|
  # Configuración del proveedor Hyper-V
  config.vm.provider "hyperv" do |h|
    h.vm_integration_services = {
      guest_service_interface: true
    }
  end

  # Configuración del nodo master
  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2204"
    master.vm.hostname = "master"
    master.vm.network "private_network", type: "dhcp"
    master.vm.provider "hyperv" do |h|
      h.memory = 2048
      h.cpus = 2
    end
    master.vm.provision "shell", path: "provision_master.sh"
  end

  # Configuración de los nodos worker
  (1..3).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "generic/ubuntu2204"
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", type: "dhcp"
      worker.vm.provider "hyperv" do |h|
        h.memory = 2048
        h.cpus = 2
      end
      worker.vm.provision "shell", inline: <<-SHELL
        while [ ! -f /vagrant/master_token ]; do
          sleep 2
        done
        K3S_URL="https://$(cat /vagrant/master_ip):6443" K3S_TOKEN=$(cat /vagrant/master_token) sh -s - agent
      SHELL
    end
  end
end
