apiVersion: external-secrets.io/v1beta1
kind: SecretStore                                                        # Kubernetes resource type
metadata:
  name: infra-vault-backend                                              # resource name
  #namespace: example
spec:
  provider:
    vault:                                                               # specifies vault as the provider
      server: "https://ec2-23-22-184-228.compute-1.amazonaws.com:8200"   # the address of your vault instance
      path: "cert/INFRA"                                                 # path for accessing the secrets
      version: "v2"                                                      # kv engine version: v1 or v2 (default)
      auth:                                                              # how to autheticate in Vault
        tokenSecretRef:
          name: "infra-vault-token"                                      # Use a secret called infra-vault-token
          key: "token"                                                   # Use this key (of the secret) to access the vault token       

# Solo para la POC: 
# Como la URL de Vault cambia cada vez que creamos la infraetsrucra de la POC, este fichero ha sido generado por la infraestructura, 
# para no tener que modificarlo a mano cada vez que generamos la infraestructura de nuevo (la URL de Vault (vaultAddr) cambia).  
# En la vida real esto no es necesario, porque la URL de Vault no  cambia.
