apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-postgres-external-secret
spec:

  # This specifies the time interval at which the ExternalSecret controller will refresh the secrets.
  refreshInterval: "5s" 

  # This object contains the reference to the Vault secret store to be used.
  secretStoreRef: 
    name: myapp-vault-backend
    kind: SecretStore

  # This specifies the target Kubernetes secret that the ExternalSecret will create.
  target: 
    name: myapp-postgres-secret             # The name of the Kubernetes secret that will be created.
    creationPolicy: Owner             # In this case, the ExternalSecret will act as the owner of the target Kubernetes Secret.

  # An array of key-value pairs that the ExternalSecret will retrieve from the Vault secret store and store in the Kubernetes secret.
  data: 
    - secretKey: POSTGRES_USER        # The key name for the secret value in the Kubernetes secret.
      remoteRef:                      # An object that contains the reference to the secret in the Vault secret store.
        key: cert/myapp/postgres      # The path to the secret in the Vault secret store
        property: DB_USER             # The name of the secret property to retrieve from the Vault secret.
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: cert/myapp/postgres
        property: DB_PASSWORD


