apiVersion: v1
kind: Secret
metadata:
  name: redmine-secret
  namespace: redmine
type: Opaque
data:
  REDMINE_DB_POSTGRES: "cmVkbWluZS1wb3N0Z3Jlc3Fs" # "redmine-postgresql" en base64
  REDMINE_DB_USERNAME: "cmVkbWluZQ==" # "redmine" en base64
  REDMINE_DB_PASSWORD: "cmVkbWluZV9wYXNzd29yZA==" # "redmine_password" en base64
  REDMINE_DB_DATABASE: "cmVkbWluZV9wcm9kdWN0aW9u" # "redmine_production" en base64
