apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: redmine
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql
  namespace: redmine
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
