apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd-platform
  annotations:
    #nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /argocd/$1
spec:
  rules:
  - http:
      paths:
      - path: /argocd/(.*)
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
    # - host: minilab.local
