apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /argocd/$1
spec:
  ingressClassName: nginx
  rules:
  - host: #megadrive.local
    http:
      paths:
      - path: /argocd/(.*)
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 8080

# - host: minilab.local
